// 一般的な英単語リスト（stopwords）
// これらの単語は「難しい単語」の候補から除外される
// 出典: 英語の最頻出単語リストから抽出

export const STOPWORDS_EN = new Set([
    // 冠詞・代名詞
    'a', 'an', 'the', 'this', 'that', 'these', 'those',
    'i', 'you', 'he', 'she', 'it', 'we', 'they', 'me', 'him', 'her', 'us', 'them',
    'my', 'your', 'his', 'its', 'our', 'their', 'mine', 'yours', 'hers', 'ours', 'theirs',
    'myself', 'yourself', 'himself', 'herself', 'itself', 'ourselves', 'themselves',
    'who', 'whom', 'whose', 'which', 'what', 'whoever', 'whatever', 'whichever',

    // be動詞・助動詞
    'be', 'am', 'is', 'are', 'was', 'were', 'been', 'being',
    'have', 'has', 'had', 'having',
    'do', 'does', 'did', 'doing', 'done',
    'will', 'would', 'shall', 'should', 'may', 'might', 'must', 'can', 'could',

    // 前置詞・接続詞
    'in', 'on', 'at', 'to', 'for', 'of', 'with', 'by', 'from', 'as', 'into',
    'through', 'during', 'before', 'after', 'above', 'below', 'between', 'under',
    'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how',
    'all', 'each', 'every', 'both', 'few', 'more', 'most', 'other', 'some', 'such',
    'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very',
    'and', 'but', 'or', 'if', 'because', 'until', 'while', 'although', 'though',

    // 一般動詞（基本形）
    'get', 'got', 'getting', 'gets',
    'go', 'goes', 'went', 'going', 'gone',
    'come', 'comes', 'came', 'coming',
    'make', 'makes', 'made', 'making',
    'take', 'takes', 'took', 'taken', 'taking',
    'see', 'sees', 'saw', 'seen', 'seeing',
    'know', 'knows', 'knew', 'known', 'knowing',
    'think', 'thinks', 'thought', 'thinking',
    'want', 'wants', 'wanted', 'wanting',
    'use', 'uses', 'used', 'using',
    'find', 'finds', 'found', 'finding',
    'give', 'gives', 'gave', 'given', 'giving',
    'tell', 'tells', 'told', 'telling',
    'say', 'says', 'said', 'saying',
    'ask', 'asks', 'asked', 'asking',
    'work', 'works', 'worked', 'working',
    'seem', 'seems', 'seemed', 'seeming',
    'feel', 'feels', 'felt', 'feeling',
    'try', 'tries', 'tried', 'trying',
    'leave', 'leaves', 'left', 'leaving',
    'call', 'calls', 'called', 'calling',
    'keep', 'keeps', 'kept', 'keeping',
    'let', 'lets', 'letting',
    'begin', 'begins', 'began', 'begun', 'beginning',
    'put', 'puts', 'putting',
    'mean', 'means', 'meant', 'meaning',
    'become', 'becomes', 'became', 'becoming',
    'show', 'shows', 'showed', 'shown', 'showing',
    'hear', 'hears', 'heard', 'hearing',
    'play', 'plays', 'played', 'playing',
    'run', 'runs', 'ran', 'running',
    'move', 'moves', 'moved', 'moving',
    'live', 'lives', 'lived', 'living',
    'believe', 'believes', 'believed', 'believing',
    'hold', 'holds', 'held', 'holding',
    'bring', 'brings', 'brought', 'bringing',
    'happen', 'happens', 'happened', 'happening',
    'write', 'writes', 'wrote', 'written', 'writing',
    'sit', 'sits', 'sat', 'sitting',
    'stand', 'stands', 'stood', 'standing',
    'lose', 'loses', 'lost', 'losing',
    'pay', 'pays', 'paid', 'paying',
    'meet', 'meets', 'met', 'meeting',
    'include', 'includes', 'included', 'including',
    'continue', 'continues', 'continued', 'continuing',
    'set', 'sets', 'setting',
    'learn', 'learns', 'learned', 'learning',
    'change', 'changes', 'changed', 'changing',
    'lead', 'leads', 'led', 'leading',
    'understand', 'understands', 'understood', 'understanding',
    'watch', 'watches', 'watched', 'watching',
    'follow', 'follows', 'followed', 'following',
    'stop', 'stops', 'stopped', 'stopping',
    'create', 'creates', 'created', 'creating',
    'speak', 'speaks', 'spoke', 'spoken', 'speaking',
    'read', 'reads', 'reading',
    'spend', 'spends', 'spent', 'spending',
    'grow', 'grows', 'grew', 'grown', 'growing',
    'open', 'opens', 'opened', 'opening',
    'walk', 'walks', 'walked', 'walking',
    'win', 'wins', 'won', 'winning',
    'offer', 'offers', 'offered', 'offering',
    'remember', 'remembers', 'remembered', 'remembering',
    'love', 'loves', 'loved', 'loving',
    'consider', 'considers', 'considered', 'considering',
    'appear', 'appears', 'appeared', 'appearing',
    'buy', 'buys', 'bought', 'buying',
    'wait', 'waits', 'waited', 'waiting',
    'serve', 'serves', 'served', 'serving',
    'die', 'dies', 'died', 'dying',
    'send', 'sends', 'sent', 'sending',
    'expect', 'expects', 'expected', 'expecting',
    'build', 'builds', 'built', 'building',
    'stay', 'stays', 'stayed', 'staying',
    'fall', 'falls', 'fell', 'fallen', 'falling',
    'cut', 'cuts', 'cutting',
    'reach', 'reaches', 'reached', 'reaching',
    'kill', 'kills', 'killed', 'killing',
    'remain', 'remains', 'remained', 'remaining',
    'suggest', 'suggests', 'suggested', 'suggesting',
    'raise', 'raises', 'raised', 'raising',
    'pass', 'passes', 'passed', 'passing',
    'sell', 'sells', 'sold', 'selling',
    'require', 'requires', 'required', 'requiring',
    'report', 'reports', 'reported', 'reporting',
    'decide', 'decides', 'decided', 'deciding',
    'pull', 'pulls', 'pulled', 'pulling',

    // 一般名詞
    'people', 'person', 'man', 'woman', 'child', 'children', 'boy', 'girl',
    'time', 'year', 'years', 'day', 'days', 'week', 'weeks', 'month', 'months',
    'way', 'ways', 'thing', 'things', 'place', 'places', 'case', 'cases',
    'point', 'points', 'part', 'parts', 'group', 'groups', 'number', 'numbers',
    'world', 'life', 'hand', 'hands', 'side', 'sides', 'area', 'areas',
    'home', 'house', 'room', 'water', 'money', 'story', 'stories',
    'fact', 'facts', 'right', 'rights', 'study', 'studies', 'book', 'books',
    'eye', 'eyes', 'job', 'jobs', 'word', 'words', 'business', 'issue', 'issues',
    'company', 'companies', 'system', 'systems', 'program', 'programs',
    'question', 'questions', 'government', 'country', 'countries',
    'problem', 'problems', 'service', 'services', 'friend', 'friends',
    'president', 'team', 'teams', 'minute', 'minutes', 'idea', 'ideas',
    'head', 'body', 'information', 'power', 'family', 'families',
    'development', 'war', 'history', 'party', 'parties', 'result', 'results',
    'morning', 'reason', 'reasons', 'research', 'girl', 'guy', 'moment', 'moments',
    'air', 'teacher', 'teachers', 'force', 'education', 'food', 'car', 'cars',

    // 形容詞
    'good', 'better', 'best', 'bad', 'worse', 'worst',
    'new', 'old', 'young', 'long', 'short', 'little', 'big', 'small', 'large',
    'high', 'low', 'great', 'important', 'different', 'same', 'able',
    'last', 'first', 'next', 'early', 'late', 'public', 'possible', 'sure',
    'free', 'right', 'wrong', 'real', 'whole', 'certain', 'clear', 'full',
    'special', 'easy', 'hard', 'strong', 'true', 'false', 'necessary',
    'political', 'social', 'national', 'local', 'available', 'likely',
    'human', 'common', 'major', 'current', 'recent', 'private',

    // 副詞
    'just', 'also', 'now', 'even', 'still', 'already', 'always', 'never',
    'often', 'ever', 'sometimes', 'usually', 'well', 'back', 'much', 'really',
    'almost', 'enough', 'probably', 'actually', 'especially', 'perhaps',
    'however', 'together', 'certainly', 'simply', 'generally', 'indeed',
    'quickly', 'slowly', 'finally', 'exactly', 'directly', 'recently',
    'usually', 'carefully', 'clearly', 'completely', 'easily',

    // 数字関連
    'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
    'first', 'second', 'third', 'fourth', 'fifth', 'hundred', 'thousand', 'million',
    'half', 'quarter', 'percent', 'nothing', 'everything', 'something', 'anything',

    // ビジネス基本語（簡単なもの）
    'about', 'after', 'again', 'against', 'around', 'away',
    'market', 'markets', 'price', 'prices', 'product', 'products',
    'customer', 'customers', 'client', 'clients', 'office', 'offices',
    'project', 'projects', 'meeting', 'meetings', 'email', 'emails',
    'website', 'internet', 'online', 'computer', 'computers',
    'phone', 'phones', 'call', 'calls', 'message', 'messages',

    // その他よく使う語
    'today', 'tomorrow', 'yesterday', 'tonight', 'tonight',
    'please', 'thank', 'thanks', 'sorry', 'okay', 'yes', 'no',
    'hello', 'goodbye', 'welcome', 'help', 'need', 'needs', 'needed',
]);

/**
 * 単語が一般語かどうかをチェック
 */
export function isStopword(word: string): boolean {
    return STOPWORDS_EN.has(word.toLowerCase());
}
